// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC0IxYQQxhlP0xoPB2uRyFe6r3dxC-VPM',
    appId: '1:214790324249:web:44adbbc862879c38766a88',
    messagingSenderId: '214790324249',
    projectId: 'lineup-e2dda',
    authDomain: 'lineup-e2dda.firebaseapp.com',
    storageBucket: 'lineup-e2dda.appspot.com',
    measurementId: 'G-RSF7Y2WHX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVZHXvA-6jwFuS2UJc_50H73K-UaRAWao',
    appId: '1:214790324249:android:cfcdb2fda0b25fc2766a88',
    messagingSenderId: '214790324249',
    projectId: 'lineup-e2dda',
    storageBucket: 'lineup-e2dda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosrSNBdGkclqDOTV-TZRLMOPhttw465U',
    appId: '1:214790324249:ios:870ac98f9b733830766a88',
    messagingSenderId: '214790324249',
    projectId: 'lineup-e2dda',
    storageBucket: 'lineup-e2dda.appspot.com',
    iosClientId: '214790324249-4gaqo6p4nrl652ikivrffekq5v9vik8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.lineup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCosrSNBdGkclqDOTV-TZRLMOPhttw465U',
    appId: '1:214790324249:ios:95710906ed9d1497766a88',
    messagingSenderId: '214790324249',
    projectId: 'lineup-e2dda',
    storageBucket: 'lineup-e2dda.appspot.com',
    iosClientId: '214790324249-po58o4qvfgspo0rr4k4k4gg6gt3o1r71.apps.googleusercontent.com',
    iosBundleId: 'com.example.lineup.RunnerTests',
  );
}
